<a href="https://colab.research.google.com/github/sun9huni/first-repository/blob/main/0618_%EC%9B%8C%EB%93%9C_%EC%9E%84%EB%B2%A0%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 53.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 494.1/494.1 kB 18.7 MB/s eta 0:00:00


In [2]:
!pip install nltk

In [3]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 65.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 88.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 15.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
thinc 8.3.6 req

In [1]:
import re
from konlpy.tag import Okt
from collections import Counter
print("임포트 완료")

임포트 완료


In [2]:
text = "임금님 귀는 당나귀 귀! 임금님 귀는 당나귀 귀! 실컷~ 소리치고 나니 속이 확 뚫려 살 것 같았어."
text

'임금님 귀는 당나귀 귀! 임금님 귀는 당나귀 귀! 실컷~ 소리치고 나니 속이 확 뚫려 살 것 같았어.'

- 특수문자는 자연어 처리에서 큰 의미를 가지지 못한다. 정규 표현식을 사용해 특수문자를 제거한다.
- 한글, 공백을 제외한 모든 문자를 표현하는 regex : [^ㄱ-ㅎㅏ-ㅣ가-힣 ]


In [3]:
reg = re.compile("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]")
text = reg.sub('', text)
print(text)

임금님 귀는 당나귀 귀 임금님 귀는 당나귀 귀 실컷 소리치고 나니 속이 확 뚫려 살 것 같았어


- 한국어는 주로 형태소 분석기를 통해서 토큰 단위를 나눠준다.
- KoNLPy에 내장된 Okt 형태소 분석기를 사용

In [4]:
okt = Okt()
tokens = okt.morphs(text)
print(tokens)

['임금님', '귀', '는', '당나귀', '귀', '임금님', '귀', '는', '당나귀', '귀', '실컷', '소리', '치고', '나니', '속이', '확', '뚫려', '살', '것', '같았어']


- 토큰을 바탕으로 단어장 만들기
- 빈도수가 높은 단어일수록 낮은 정수 부여
- 파이썬의 Counter 서브클래스를 사용해서 단어의 빈도를 카운트


In [5]:
vocab = Counter(tokens)
print(vocab)

Counter({'귀': 4, '임금님': 2, '는': 2, '당나귀': 2, '실컷': 1, '소리': 1, '치고': 1, '나니': 1, '속이': 1, '확': 1, '뚫려': 1, '살': 1, '것': 1, '같았어': 1})


- 단어가 key, 빈도수가 value로 지정

In [6]:
vocab['임금님']

2

- most_common()는 상위 빈도수를 가진 단어를 주어진 수만큼 리컨한다.
- 등장 빈도 수 상위 5개만 단어장으로 저장

In [9]:
vocab_size = 5
vocab = vocab.most_common(vocab_size) # 등장 빈도수가 높은 상위 5개의 단어만 저장
print(vocab)

[('귀', 4), ('임금님', 2), ('는', 2), ('당나귀', 2), ('실컷', 1)]


- 높은 빈도수를 가진 단어일수록 낮은 정수 인덱스를 부여

In [10]:
word2idx = {word[0] : index + 1 for index, word in enumerate(vocab)}
print(word2idx)

{'귀': 1, '임금님': 2, '는': 3, '당나귀': 4, '실컷': 5}


- one-hot encoding 함수를 만들어 각 단어를 one-hot vector로 변환

In [11]:
def one_hot_encoding(word, word2index):
  one_hot_vector = [0]*(len(word2index))
  index = word2index[word]
  one_hot_vector[index-1] = 1
  return one_hot_vector
print('슝=3')


슝=3


In [12]:
# 임금님 단어의 onehotvector
one_hot_encoding("임금님", word2idx)

[0, 1, 0, 0, 0]

케라스를 통한 One-hot-encoding
Tokenizer와 to_categorical 사용

In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
print("임포트 완료")

임포트 완료


In [16]:
text = [['강아지', '고양이', '강아지'],['애교', '고양이'], ['컴퓨터', '노트북']]
text

[['강아지', '고양이', '강아지'], ['애교', '고양이'], ['컴퓨터', '노트북']]

- keras Tokenizer는 주어진 text로부터 Vocab을 만들고, 각 단어에 고유한 정수를 mapping

In [18]:
t = Tokenizer()
t.fit_on_texts(text)
print(t.word_index)

{'강아지': 1, '고양이': 2, '애교': 3, '컴퓨터': 4, '노트북': 5}


In [19]:
# 단어장의 크기를 voacb_size에 저장
vocab_size = len(t.word_index) + 1
print("슝=3")

슝=3


In [20]:
# 단어장에 속한 단어들로 구성된 텍스트 시퀀스는 케라스 토크나이저를 통해 정수 시퀀스로 변환가능
sub_text = ['강아지', '고양이', '강아지', '컴퓨터']
encoded = t.texts_to_sequences([sub_text])
print(encoded)

[[1, 2, 1, 4]]


In [23]:
# 이렇게 변환된 정수 시퀀스는 to_categorical()을 사용해 원-핫 벡터의 시퀀스로 변환 가능
one_hot = to_categorical(encoded, num_classes = vocab_size)
print(one_hot)

[[[0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0.]]]


Word2Vec
- Word2Vec은 은닉층이 1개라서 딥 러닝이라기보다는 얕은 신경망(Shallow Neural Network) 을 학습

(1) 분포가설
- 분포 가설은 비슷한 문맥에서 같이 등장하는 경향이 있는 단어들은 비슷한 의미를 가진다는 가설이다.

(2) CBoW(Continuous Bag of words)
- 주변에 있는 단어들을 통해 중간에 있는 단어들을 예측하는 방법
- 단어의 범위를 window라고 한다.
- 윈도우 크기를 정한 후 원도우를 계속 움직이면서 학습 위한 데이터셋을 만드는 방법이 sliding window
- 이렇게 선택된 데이터셋에서 단어 각각은 원-핫 인코딩되어 원-핫 벡터가 되고, 원-핫 벡터가 CBoW나 Skip-gram의 입력이 된다.
- 원-핫 벡터와 가중치 행렬과의 곱은 가중치 행렬의 i 위치에 있는 행을 그대로 가져오는 것과 동일
- 이를  룩업 테이블(lookup table)이라고 한다.
- 룩업 데이블을 거쳐 생긴 벡터들을 모두 합하거나, 평균을 구한 값을 최종 은닉층의 결과로 한다.
- Word2Vec 은닉층은 활성화 함수가 존재하지 않고, 단순 가중치 행렬과의 곱셈만을 수행하기에 투사층(projection layer)라고 한다.
- 은닉층에서 생성된 N차원의 벡터는 두 번째 가중치 행렬과 곱해진다. 이 가중치 행렬의 크기는 (N x V), 곱셈의 결과로 나오는 벡터의 차원은 V이다.
- 출력층은 softmax를 사용하므로 V 차원의 벡터는 활성화 함수를 거쳐 모든 총합이 1이 되는 벡터로 변경된다.
- CBoW는 이 출력층의 벡터를 중심 단어의 원-핫 벡터와의 손실(loss)을 최소화 하도록 학습

(3) Skip-Gram
- 중간에 있는 단어로 주변 단어를 예측하는 방법
- 은닉층에서 다수의 벡터의 덧셈과 평균을 구하는 과정이 없다.
- 네거티브 샘플링(Negative Sampling)을 사용한다.
- 네거티브 샘플링은 연산량을 줄이기 위해 다중 클래스 분류 문제를 시그모이드 함수를 이용한 이진 분류 문제로 바꾼다.
- 랜덤으로 단어장에 있는 아무 단어나 가져와 target word로 하는 거짓 데이터셋을 만들고 0으로 레이블링을 해주는 것

## Word2Vec (4) 영어 Word2Vec 실습과 OOV 문제

In [24]:
import nltk
nltk.download('abc')
nltk.download('punkt_tab')

[nltk_data] Downloading package abc to /root/nltk_data...
[nltk_data]   Unzipping corpora/abc.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [25]:
from nltk.corpus import abc
corpus = abc.sents()
print("슝~")

슝~


In [26]:
print(corpus[:3])

[['PM', 'denies', 'knowledge', 'of', 'AWB', 'kickbacks', 'The', 'Prime', 'Minister', 'has', 'denied', 'he', 'knew', 'AWB', 'was', 'paying', 'kickbacks', 'to', 'Iraq', 'despite', 'writing', 'to', 'the', 'wheat', 'exporter', 'asking', 'to', 'be', 'kept', 'fully', 'informed', 'on', 'Iraq', 'wheat', 'sales', '.'], ['Letters', 'from', 'John', 'Howard', 'and', 'Deputy', 'Prime', 'Minister', 'Mark', 'Vaile', 'to', 'AWB', 'have', 'been', 'released', 'by', 'the', 'Cole', 'inquiry', 'into', 'the', 'oil', 'for', 'food', 'program', '.'], ['In', 'one', 'of', 'the', 'letters', 'Mr', 'Howard', 'asks', 'AWB', 'managing', 'director', 'Andrew', 'Lindberg', 'to', 'remain', 'in', 'close', 'contact', 'with', 'the', 'Government', 'on', 'Iraq', 'wheat', 'sales', '.']]


In [32]:
from nltk.corpus import abc
corpus = list(abc.sents())
corpus_length = len(corpus)
print('코퍼스의 크기 :', corpus_length)

코퍼스의 크기 : 29059


In [33]:
from gensim.models import Word2Vec

model = Word2Vec(sentences = corpus, vector_size = 100, window = 5, min_count = 5, workers = 4, sg = 0)
print('모델 학습 완료')

모델 학습 완료


- vector size = 학습 후 Embedding vector의 차원
- window = Context Window 크기
- min_count = 단어 최소 빈도수 제한 (빈도가 적은 단어들은 학습하지 않아요.)
- workers = 학습을 위한 프로세스 수
- sg = 0은 CBoW, 1은 Skip-gram.

In [34]:
# Word2Vec는 입력한 단어에 대해서 가장 코사인 유사도가 높은 단어들을 출력하는 model.wv.most_similar를 지원
model_result = model.wv.most_similar('man')
print(model_result)

[('skull', 0.9349513649940491), ('third', 0.9185877442359924), ('woman', 0.9181984066963196), ('ten', 0.8983795642852783), ('star', 0.8982238173484802), ('fifth', 0.8978276252746582), ('field', 0.8941973447799683), ('galaxy', 0.8939309120178223), ('dog', 0.8935268521308899), ('tunnel', 0.8911997675895691)]


In [35]:
# 모델 저장 및 로드
from gensim.models import KeyedVectors

model.wv.save_word2vec_format('./w2v')
loaded_model = KeyedVectors.load_word2vec_format("./w2v")
print("모델  load 완료!")

모델  load 완료!


In [36]:
# 로드한 모델이 이전과 동일한 결과를 출력하는지 테스트
model_result = loaded_model.most_similar("man")
print(model_result)

[('skull', 0.9349513649940491), ('third', 0.9185877442359924), ('woman', 0.9181984066963196), ('ten', 0.8983795642852783), ('star', 0.8982238173484802), ('fifth', 0.8978276252746582), ('field', 0.8941973447799683), ('galaxy', 0.8939309120178223), ('dog', 0.8935268521308899), ('tunnel', 0.8911997675895691)]


In [37]:
# 에러가 나더라도 놀라지 마세요.
loaded_model.most_similar('overacting')
## OOV 문제

KeyError: "Key 'overacting' not present in vocabulary"

In [38]:
loaded_model.most_similar('memorry')

KeyError: "Key 'memorry' not present in vocabulary"

## 17-9. 임베딩 벡터의 시각화
- 임베딩 프로젝터(embedding projector) 를 사용해서 임베딩 벡터들을 시각화
- 어떤 임베팅 벡터들이 가까운 거리에 군집이 되어 있고, 특정 임베딩 벡터와 유클리드 거리나 코사인 유사도가 높은지 확인 가능



## 17-10. FastText
- 매커니즘 자체는 Word2Vec을 따르지만, 문자 단위 n-gram(character-level n-gram) 표현을 학습한다
- FastText는 단어 내부의 내부 단어(subwords)들을 학습한다는 아이디어
- n은 단어들이 얼마나 분리되는지 결정하는 하이퍼파라미터
- 시작과 끝을 의미하는 <, >를 도입
- <pa, par, art, rti, tia, ial, al>라는 6개의 내부 단어(subword) 토큰을 벡터로 만든다.
- 여기에 추가적으로 기존 단어에 <, 와 >를 붙인 토큰 <partial>을 벡터화한다.
- 이렇게 벡터화된 n-gram 벡터들의 총합을 해당 단어의 벡터로 취한다.
- FastText도 Word2Vec과 마찬가지로 네거티브 샘플링을 사용하여 학습한다.
- Word2Vec과 다른 점은 학습 과정에서 중심 단어에 속한 문자 단위 n-gram 단어 벡터들을 모두 업데이트한다는 점
- FastText는 Word2Vec과 달리 OOV와 오타에 강건하다(robust) 는 특징
- 단어장에 없는 단어라도, 해당 단어의 n-gram이 다른 단어에 존재하면 이로부터 벡터값을 얻는다는 원리에 기인

In [39]:
# word2vec 모델 메타정보 및 텐서 내보내기
!python -m gensim.scripts.word2vec2tensor --input ./w2v --output ./w2v

2025-06-18 07:40:53,776 - word2vec2tensor - INFO - running /usr/local/lib/python3.11/dist-packages/gensim/scripts/word2vec2tensor.py --input ./w2v --output ./w2v
2025-06-18 07:40:53,776 - keyedvectors - INFO - loading projection weights from ./w2v
2025-06-18 07:40:54,489 - utils - INFO - KeyedVectors lifecycle event {'msg': 'loaded (10363, 100) matrix of type float32 from ./w2v', 'binary': False, 'encoding': 'utf8', 'datetime': '2025-06-18T07:40:54.486607', 'gensim': '4.3.3', 'python': '3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]', 'platform': 'Linux-6.1.123+-x86_64-with-glibc2.35', 'event': 'load_word2vec_format'}
2025-06-18 07:40:55,249 - word2vec2tensor - INFO - 2D tensor file saved to ./w2v_tensor.tsv
2025-06-18 07:40:55,249 - word2vec2tensor - INFO - Tensor metadata file saved to ./w2v_metadata.tsv
2025-06-18 07:40:55,249 - word2vec2tensor - INFO - finished running word2vec2tensor.py


In [40]:
from gensim.models import FastText
fasttext_model = FastText(corpus, window=5, min_count=5, workers=4, sg=1)
print("FastText 학습 완료!")

FastText 학습 완료!


In [41]:
fasttext_model.wv.most_similar('overacting')

[('extracting', 0.9463399052619934),
 ('lifting', 0.9393213987350464),
 ('losing', 0.9376756548881531),
 ('blushing', 0.9345923662185669),
 ('fluctuating', 0.9313043355941772),
 ('mixing', 0.9310101866722107),
 ('attracting', 0.9308171272277832),
 ('shifting', 0.9307165145874023),
 ('emptying', 0.9299069046974182),
 ('rotating', 0.9279723167419434)]

In [42]:
fasttext_model.wv.most_similar('memoryy')

[('memory', 0.9513688087463379),
 ('musical', 0.8755364418029785),
 ('intelligence', 0.8468678593635559),
 ('mechanical', 0.8463777303695679),
 ('emotion', 0.8421338796615601),
 ('visual', 0.8412631154060364),
 ('actual', 0.8411545753479004),
 ('experience', 0.8390754461288452),
 ('mechanism', 0.8361741304397583),
 ('cognitive', 0.8358390927314758)]

- 'overacting'이 단어장에 없던 단어임에도 정상적으로 임베딩 벡터값이 계산되어 유사 단어 10개를 출력하는 것을 볼 수 있다. 이는 오타를 가정한 단어 'memoryy'에서도 마찬가지이다.

## 17-11. GloVe
글로브(Global Vectors for Word Representation, GloVe)는 카운트 기반과 예측 기반 두 가지 방법을 모두 사용

- DTM의 경우에는 단어 간 유사도를 반영할 수 없고, 대부분의 값이 0인 희소 표현이라는 특징, DTM을 차원 축소하여 밀집 표현(dense representation)으로 임베딩 하는 방법이 LSA(Latent Semantic Analysis)
- LSA는 DTM에 특잇값 분해를 사용해 잠재적 의미를 이끌어내는 방법론이다.

LSA 같은 카운트 기반 임베딩 방법의 한계점
- 차원 축소의 특성으로 인해 새로운 단어 추가 시 다시 DTM을 만들어 새로 차원 축소를 해야 한다.
- 단어 벡터 간 유사도를 계산하는 측면에서 Word2Vec보다 성능이 떨어진다.

예측 기반의 방법 은 Word2Vec과 같은 방법
- 인공 신경망이 예측한 값으로부터 실제 레이블과의 오차를 구하고, 손실 함수를 통해서 인공 신경망을 학습하는 방식
- LSA보다 단어 벡터 간 유사도를 구하는 능력은 뛰어나지만, LSA처럼 corpus의 전체적인 통계 정보를 활용하지는 못한다는 점이 한계


### 윈도우 기반 동시 등장 행렬(Window based Co-occurrence Matrix)
- 행과 열을 전체 vocab의 단어들로 구성하고, 어떤 i 단어의 window Size 내에서 k 단어가 등장한 횟수를 i행 k열에 기재한 행렬
- 전치(transpose)해도 동일한 행렬이 된다는 특징

### 동시 등장 확률(Co-occurrence Probability)
- 동시 등장 행렬로부터 특정 단어 i의 전체 등장 횟수를 카운트하고, 특정 단어 i가 등장했을 때 어떤 단어 k가 등장한 횟수를 카운트하여 계산한 조건부 확률
- i를 중심 단어(center word), k를 주변 단어(context word)라고 한다.

### GloVe의 손실 함수 설계하기
- 동시 등장 행렬(카운트 기반)의 동시 등장 확률을 이용해 손실 함수(예측 기반)를 설계
- GloVe는 전체 corpus에서의 동시 등장 빈도의 로그값과 중심 단어 벡터와 주변 단어 벡터의 내적값의 차이가 최소화되도록 두 벡터의 값을 학습하는 것
- GloVe의 연구진은 동시 등장 행렬에서 동시 등장 빈도의 값이 굉장히 낮은 경우에는 거의 도움이 되지 않는 정보라고 판단했습니다. 그래서 이에 대한 가중치를 주기 위해서 GloVe 연구진이 선택한 것은 바로
동시 등장 빈도의 값에 영향을 받는 가중치 함수(Weighting function)를 도입



In [43]:
import gensim.downloader as api
glove_model = api.load("glove-wiki-gigaword-50")  # glove vectors 다운로드
glove_model.most_similar("dog")  # 'dog'과 비슷한 단어 찾기

[==================================================] 100.0% 66.0/66.0MB downloaded


[('cat', 0.9218004941940308),
 ('dogs', 0.8513158559799194),
 ('horse', 0.7907583713531494),
 ('puppy', 0.7754920721054077),
 ('pet', 0.7724708318710327),
 ('rabbit', 0.7720814347267151),
 ('pig', 0.7490062117576599),
 ('snake', 0.7399188876152039),
 ('baby', 0.7395570278167725),
 ('bite', 0.7387937307357788)]

In [44]:
glove_model.most_similar('overacting')

[('impudence', 0.7842012047767639),
 ('puerile', 0.7816032767295837),
 ('winningly', 0.7644237875938416),
 ('grossness', 0.7576098442077637),
 ('deconstructions', 0.748936653137207),
 ('over-the-top', 0.7460805773735046),
 ('buffoonery', 0.746045708656311),
 ('impetuosity', 0.7415392398834229),
 ('sophomoric', 0.736961841583252),
 ('zaniness', 0.7353197336196899)]

In [45]:
glove_model.most_similar('memoryy')
# GloVe는 Word2Vec과 같이 OOV 문제를 가지고 있어서 'memoryy'라는 단어는 인식하지 못합니다

KeyError: "Key 'memoryy' not present in vocabulary"